ClinicaMedicaWeb/Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ClinicaMedicaWeb.Models
{
    public class Consulta
    {
        [DisplayName("Identificador da Consulta")]
        public int Id { get; set; }

        public int? PacienteId { get; set; }

        public Paciente Paciente { get; set; }

        public int? MedicoId { get; set; }

        public Medico Medico { get; set; }

        public int? SecretariaId { get; set; }

        public Secretaria Secretaria { get; set; }

        [Required(ErrorMessage = "Data da Consulta")]
        [DisplayName("Data da Consulta")]
        [DataType(DataType.Date)]
        public DateTime DataConsulta { get; set; }

        [Required(ErrorMessage = "Hora da Consulta")]
        [DisplayName("Hora da Consulta")]
        [DataType(DataType.Time)]
        public DateTime HoraConsulta { get; set; }

        [DataType(DataType.Date)]
        public DateTime DataCadastroConsulta { get; set; }

        [DataType(DataType.Time)]
        public DateTime HoraInicio { get; set; }

        [DataType(DataType.Time)]
        public DateTime HoraFim { get; set; }

        [Required(ErrorMessage = "Pagamento da Consulta")]
        [DisplayName("Pagamento da Consulta")]
        public string Pagamento { get; set; }

        public bool Presenca { get; set; }

        public string Observacao { get; set; }

        public StatusConsulta Status { get; set; }

        public string MotivoCancelamento { get; set; }

        public int? SecretariaIdCancelamento { get; set; }

        [DataType(DataType.Date)]
        public DateTime DataCancelamento { get; set; }

        [NotMapped]
        public string NomeMedico { get; set; }

        [NotMapped]
        public string NomePaciente { get; set; }

        [NotMapped]
        [MinLength(8, ErrorMessage = "Utilize 8 caracteres")]
        [MaxLength(8, ErrorMessage = "Utilize ao máximo 8 caracteres")]
        [DataType(DataType.Password)]
        public string Chave { get; set; }

        public bool Privado { get; set; }
    }
}

ClinicaMedicaWeb/Controllers/ConsultaController.cs
using ClinicaMedicaWeb.Data;
using ClinicaMedicaWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClinicaMedicaWeb.Controllers
{
    [Authorize(Roles = "Secretaria")]
    public class ConsultaController : Controller
    {
        private readonly DataContext dataContext;

        public ConsultaController(DataContext dc)
        {
            dataContext = dc;
        }

        public IActionResult Create()
        {
            var listaMedico = dataContext.TBMedico.Where(x => x.Status == Status.Ativo).OrderBy(x => x.Nome).Select(m => new
            {
                MedicoId = m.Id,
                MedicoNome = m.Nome
            }).ToList();

            ViewBag.Medicos = new SelectList(listaMedico, "MedicoId", "MedicoNome");

            var listaPaciente = dataContext.TBPaciente.Where(x => x.Status == Status.Ativo).OrderBy(x => x.Nome).Select(m => new
            {
                PacienteId = m.Id,
                PacienteNome = m.Nome
            }).ToList();

            ViewBag.Pacientes = new SelectList(listaPaciente, "PacienteId", "PacienteNome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Consulta consulta)
        {
            var listaMedico = dataContext.TBMedico.Where(x => x.Status == Status.Ativo).OrderBy(x => x.Nome).Select(m => new
            {
                MedicoId = m.Id,
                MedicoNome = m.Nome
            }).ToList();

            ViewBag.Medicos = new SelectList(listaMedico, "MedicoId", "MedicoNome");

            var listaPaciente = dataContext.TBPaciente.Where(x => x.Status == Status.Ativo).OrderBy(x => x.Nome).Select(m => new
            {
                PacienteId = m.Id,
                PacienteNome = m.Nome
            }).ToList();

            ViewBag.Pacientes = new SelectList(listaPaciente, "PacienteId", "PacienteNome");

            List<Consulta> lista = dataContext.TBConsulta.Where(x => x.Status != StatusConsulta.Cancelado).ToList();

            if (lista != null)
            {
                foreach (Consulta consulta2 in lista)
                {
                    if (consulta2.MedicoId == consulta.MedicoId)
                    {
                        if (consulta2.DataConsulta == consulta.DataConsulta && consulta2.HoraConsulta == consulta.HoraConsulta)
                        {
                            ViewBag.TipoMensagem = "ERRO";
                            ViewBag.Mensagem = "Há uma consulta agendada neste horário!";
                            return View();

                        }
                    }
                }
            }
            if (consulta.DataConsulta < DateTime.Now.Date)
            {
                ViewBag.TipoMensagem = "ERRO";
                ViewBag.Mensagem = "A consulta não pode ser agendada em uma data ou hora passada!";
                return View();
            }

            consulta.Status = StatusConsulta.Agendado;
            consulta.DataCadastroConsulta = DateTime.Now;
            consulta.Presenca = false;
            consulta.Secretaria = null;

            dataContext.TBConsulta.Add(consulta);
            dataContext.SaveChanges();

            TempData["TipoMensagem"] = "SUCESSO";
            TempData["Mensagem"] = "Consulta agendada com sucesso";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? Id)
        {
            if (Id.HasValue)
            {
                Consulta consulta = dataContext.TBConsulta.Include(x => x.Paciente).Include(x => x.Medico).FirstOrDefault(x => x.Id == Id);

                if (consulta != null)
                    return View(consulta);
            }

            return NoContent();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Consulta consulta)
        {
            Consulta consulta2 = dataContext.TBConsulta.Include(x => x.Paciente).Include(x => x.Medico).FirstOrDefault(x => x.Id == consulta.Id);

            List<Consulta> lista = dataContext.TBConsulta.Where(x => x.Id != consulta.Id).Where(x => x.Status != StatusConsulta.Cancelado).ToList();

            if (lista != null)
            {
                foreach (Consulta consulta3 in lista)
                {
                    if (consulta3.MedicoId == consulta2.MedicoId)
                    {
                        if (consulta3.DataConsulta == consulta.DataConsulta && consulta3.HoraConsulta == consulta.HoraConsulta)
                        {
                            ViewBag.TipoMensagem = "ERRO";
                            ViewBag.Mensagem = "Há uma consulta agendada neste horário!";
                            return View();
                        }
                    }
                }
            }

            if (consulta.DataConsulta < DateTime.Now.Date)
            {
                ViewBag.TipoMensagem = "ERRO";
                ViewBag.Mensagem = "A consulta não pode ser agendada em uma data ou hora passada!";
                return View();
            }
            else
            {
                consulta2.DataConsulta = consulta.DataConsulta;
                consulta2.HoraConsulta = consulta.HoraConsulta;
                consulta.Medico = null;
                consulta.Paciente = null;

                ModelState.Clear();

                if (ModelState.IsValid)
                {
                    if (dataContext.TBConsulta.Any(x => x.Id == consulta.Id))
                    {
                        try
                        {
                            dataContext.TBConsulta.Update(consulta2);
                            dataContext.SaveChanges();
                        }
                        catch
                        {
                            ViewBag.MensagemErro = "A consulta não pode ser atualizada";
                            return View();
                        }

                        TempData["TipoMensagem"] = "SUCESSO";
                        TempData["Mensagem"] = "Consulta atualizada com sucesso";
                        return RedirectToAction("Index");
                    }
                }
            }
            return NoContent();
        }

        public IActionResult Delete(int? ID)
        {
            if (ID.HasValue)
            {
                Consulta consulta = dataContext.TBConsulta.FirstOrDefault(x => x.Id == ID);

                if (consulta != null)
                    return View(consulta);
            }
            return NoContent();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Consulta consulta)
        {
            Consulta consulta2 = dataContext.TBConsulta.FirstOrDefault(x => x.Id == consulta.Id);

            if (consulta2 != null)
            {
                consulta2.Status = StatusConsulta.Cancelado;
                consulta2.SecretariaIdCancelamento = consulta.SecretariaIdCancelamento;
                consulta2.DataCancelamento = DateTime.Now;
                consulta2.MotivoCancelamento = consulta.MotivoCancelamento;

                dataContext.TBConsulta.Update(consulta2);
                dataContext.SaveChanges();

                TempData["TipoMensagem"] = "SUCESSO";
                TempData["Mensagem"] = $"A consulta foi cancelada com sucesso";
                return RedirectToAction("Index");
            }
            return NoContent();
        }

        public ActionResult ConfirmarPresenca(int? ID)
        {
            if (ID.HasValue)
            {
                Consulta consulta = dataContext.TBConsulta.FirstOrDefault(x => x.Id == ID);

                if (consulta != null)
                {
                    consulta.Presenca = true;

                    dataContext.TBConsulta.Update(consulta);
                    dataContext.SaveChanges();

                    TempData["TipoMensagem"] = "SUCESSO";
                    TempData["Mensagem"] = $"A presença do paciente nesta consulta foi confirmada com sucesso";
                    return RedirectToAction("Index");
                }
            }
            return NoContent();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Consulta consulta)
        {
            if (consulta == null)
                return RedirectToAction("Index");
            else
            {
                if (consulta.NomePaciente == null && consulta.NomeMedico == null)
                {
                    consulta.NomePaciente = "";
                    consulta.NomeMedico = "";
                    List<Consulta> lista = dataContext.TBConsulta.Include(x => x.Paciente).Include(x => x.Medico).Where(x => x.Status != StatusConsulta.Cancelado).Where(x => x.Status != StatusConsulta.Finalizado).Where(x => x.DataConsulta == consulta.DataConsulta).OrderBy(a => a.DataConsulta).ToList();
                    return View(lista);
                }
                else
                {
                    if (consulta.NomePaciente != null && consulta.NomeMedico == null)
                    {
                        consulta.NomePaciente = consulta.NomePaciente.Trim().ToUpper();
                        List<Consulta> lista = dataContext.TBConsulta.Include(x => x.Paciente).Include(x => x.Medico).Where(x => x.Paciente.Nome.ToUpper().Contains(consulta.NomePaciente)).Where(x => x.Status != StatusConsulta.Cancelado).Where(x => x.Status != StatusConsulta.Finalizado).OrderBy(a => a.DataConsulta).ToList();
                        return View(lista);
                    }
                    else if (consulta.NomePaciente != null && consulta.NomeMedico != null)
                    {
                        consulta.NomePaciente = consulta.NomePaciente.Trim().ToUpper();

ClinicaMedicaWeb/Views/Consulta/Create.cshtml
@model ClinicaMedicaWeb.Models.Consulta;

@if (ViewBag.TipoMensagem != null)
{
    if (ViewBag.TipoMensagem == "ERRO")
    {
<div class="alert alert-danger">@ViewBag.Mensagem</div> }
else if (ViewBag.TipoMensagem == "SUCESSO")
{
<div class="alert alert-success">@ViewBag.Mensagem</div>}
}

<form method="post">
    <div>
        <div class="form-group">
            <label asp-for="Secretaria.Nome">Secretario(a)</label>
            <input asp-for="Secretaria.Nome" class="form-control" value="@User.Identity.Name" readonly />
            <input asp-for="SecretariaId" value="@User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Sid).Value" type="hidden" />
            <span asp-validation-for="SecretariaId" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="MedicoId">Médico</label>
            <select class="form-control" asp-for="MedicoId" asp-items="@ViewBag.Medicos"></select>
            <span type="hidden" asp-validation-for="MedicoId" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="PacienteId">Paciente</label>
            <select class="form-control" asp-for="PacienteId" asp-items="@ViewBag.Pacientes"></select>
            <span type="hidden" asp-validation-for="PacienteId" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="DataConsulta"></label>
            <input asp-for="DataConsulta" class="form-control"/>
            <span asp-validation-for="DataConsulta" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="HoraConsulta"></label>
            <input type="time" asp-for="HoraConsulta" class="form-control"/>
            <span asp-validation-for="HoraConsulta" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="Pagamento"></label>
            <select asp-for="Pagamento" class="form-control">
                <option disabled selected>Selecione</option>
                <option>Convênio</option>
                <option>Gratuito</option>
                <option>Particular</option>
            </select>
            <span asp-validation-for="Pagamento" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-secondary" asp-controller="Consulta" asp-action="Index">Cancelar</button>
            <button type="submit" class="btn btn-primary">Agendar</button>
        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClinicaMedicaWeb/Views/Consulta/Delete.cshtml
@model ClinicaMedicaWeb.Models.Consulta;

@if (ViewBag.TipoMensagem != null)
{
    if (ViewBag.TipoMensagem == "ERRO")
    {
<div class="alert alert-danger">@ViewBag.Mensagem</div> }
else if (ViewBag.TipoMensagem == "SUCESSO")
{
<div class="alert alert-success">@ViewBag.Mensagem</div>}
}

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <div>
        <div class="form-group">
            <label asp-for="Secretaria.Nome">Secretario(a)</label>
            <input asp-for="Secretaria.Nome" class="form-control" value="@User.Identity.Name" readonly />
            <input asp-for="SecretariaIdCancelamento" value="@User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Sid).Value" type="hidden" />
            <span asp-validation-for="SecretariaIdCancelamento" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="MotivoCancelamento">Motivo do Cancelamento</label>
            <textarea asp-for="MotivoCancelamento" class="form-control" rows="3"></textarea>
            <span asp-validation-for="MotivoCancelamento" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-secondary" asp-controller="Consulta" asp-action="Index">Cancelar</button>
            <button type="submit" class="btn btn-primary">Confirmar Cancelamento</button>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClinicaMedicaWeb/Views/Consulta/Edit.cshtml
@model ClinicaMedicaWeb.Models.Consulta;

@if (ViewBag.TipoMensagem != null)
{
    if (ViewBag.TipoMensagem == "ERRO")
    {
<div class="alert alert-danger">@ViewBag.Mensagem</div> }
else if (ViewBag.TipoMensagem == "SUCESSO")
{
<div class="alert alert-success">@ViewBag.Mensagem</div>}
}

<form method="post" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div>
        <div class="form-group">
            <label asp-for="Paciente.Nome">Paciente</label>
            <input asp-for="Paciente.Nome" class="form-control" readonly />
        </div>

        <div class="form-group">
            <label asp-for="Medico.Nome">Médico</label>
            <input asp-for="Medico.Nome" class="form-control" readonly />
        </div>

        <div class="form-group">
            <label asp-for="DataConsulta"></label>
            <input asp-for="DataConsulta" class="form-control" />
            <span asp-validation-for="DataConsulta" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <label asp-for="HoraConsulta"></label>
            <input type="time" asp-for="HoraConsulta" class="form-control" />
            <span asp-validation-for="HoraConsulta" class="text-danger small"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-secondary" asp-controller="Consulta" asp-action="Index">Cancelar</button>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClinicaMedicaWeb/Views/Consulta/Index.cshtml
@model IEnumerable<Consulta>;

<h2>Consultas</h2>

<div class="mb-3 mt-1">
    <a asp-action="Create"><strong>+ Agendar Nova Consulta</strong></a>
</div>

@if (TempData["TipoMensagem"] != null)
{
    if (TempData["TipoMensagem"].ToString() == "ERRO")
    {
        <div class="alert alert-danger">@TempData["Mensagem"].ToString()</div>
    }
    else if (TempData["TipoMensagem"].ToString() == "SUCESSO")
    {
        <div class="alert alert-success">@TempData["Mensagem"].ToString()</div>
    }
}

<form method="post">
    <div class="form-group">
        <input id="dateDataConsulta" name="DataConsulta" type="date" class="span4"/>

        <input id="txtNomePaciente" name="NomePaciente" class="span4" placeholder="Pesquisar por Paciente" />

        <input id="txtNomeMedico" name="NomeMedico" class="span4" placeholder="Pesquisar por Médico" />

        <button type="submit" class="btn btn-primary">Pesquisar</button>
    </div>
</form>

<form>
    <div class="modal" id="modalConfirmacao" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div>
                            <i class="fa fa-4x fa-minus-circle text-info"></i>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center" style="padding-top: 12px;">
                        <span class="h4">Tem certeza?</span>
                    </div>
                    <div>
                        <small style="text-align: center">Deseja realmente confirmar a presença do paciente? </small>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-center" style="border-top: 0px;">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-sm btn-success" asp-action="ConfirmarPresenca" id="btnConfirmar">Sim</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="container">
    <div class="row">
        <div class="col-sm-1">
            Data
        </div>
        <div align="center" class="col-sm-1">
            Hora
        </div>
        <div class="col-sm-3">
            @Html.DisplayNameFor(model => model.Paciente)
        </div>
        <div class="col-sm-3">
            @Html.DisplayNameFor(model => model.Medico)
        </div>
        <div class="col-sm-1">
            Reagendar
        </div>
        <div class="col-sm-1">
            Presença
        </div>
        <div class="col-sm-1">
            Cancelar
        </div>
    </div>

    @if (Model != null)
    {
        @foreach (Consulta consulta in Model)
        {
            <div class="row">
                <div class="col-sm-1">
                    @Html.DisplayFor(model => consulta.DataConsulta)
                </div>
                <div align="center" class="col-sm-1">
                    @Html.DisplayFor(model => consulta.HoraConsulta)
                </div>
                <div class="col-sm-3">
                    @consulta.Paciente.Nome
                </div>
                <div class="col-sm-3">
                    @consulta.Medico.Nome
                </div>
                <div class="col-sm-1 mt-1">
                    <a class='btn btn-sm btn-primary' asp-action="Edit" asp-route-id='@consulta.Id'>Reagendar</a>
                </div>
                <div class="col-sm-1 mt-1">
                    @if (consulta.Presenca == true)
                    {
                        <label class='btn btn-sm btn-success'>Confirmada</label>
                    }
                    else
                    {
                        <a class='btn btn-sm btn-outline-warning' data-toggle='modal' data-target='#modalConfirmacao' data-code='@consulta.Id'>Confirmar</a>
                    }
                </div>
                <div class="col-sm-1 mt-1">
                    <a class='btn btn-sm btn-danger' asp-action="Delete" asp-route-id='@consulta.Id'>Cancelar</a>
                </div>
            </div>
        }
    }
</div>

<script>
    window.onload = function () {
        $('#modalConfirmacao').on('show.bs.modal', function (e) {
            let code = $(e.relatedTarget).data('code');
            let s = document.getElementById('btnConfirmar').getAttribute('formaction');

            document.getElementById('btnConfirmar').removeAttribute('formaction');
            document.getElementById('btnConfirmar').setAttribute('formaction', s + '/' + code);
        });
    }
</script>